name: Demo Workflow
on: workflow_dispatch
jobs:
  myfirstjob:
    runs-on: ubuntu-latest
    steps:
      - name: sending a message
        run: echo "hello world"
      - name: sending another message
        run: echo "hello"
